language: java
script: |
  if [[ "$RELEASE_BUILD" == 'true' && "$TRAVIS_SECURE_ENV_VARS" == 'true' ]] ; then
    mvn deploy
  else
    mvn test
  fi
jdk:
- openjdk6
- openjdk7
- oraclejdk8
env:
  global:
  - secure: NLOleRANVTErubOCrf3AnljVYxzrz3Os5atObx4cc1J10JUszNYY0QhNiv+2rlK96fHdER7fkf+s+FnaQcisDDUSFMZgzNAdlFvruPnwBBw/3qHLGix0UiTLP/jc6nWQK77hFwsprHvmVdlCMymHQpm9Gw917rTg21kOEM50w98= # ARTIFACTORY_USERNAME
  - secure: cRru6TUOkGyszzlvWPF1tNXkLeq3cSSkkxmwRSxgTmHkgzxmA5ZgR4mnT2pPPuGJ5nuOR0MBeplsl/KxSXSbDPqG0nxODVmvDq5j2Y8sZgSZY8mCYt7f/oHo6l9KjSPhx/hbo6eiWHVY59nQZ3m71iJo2TdcTu/+zYJDnLt5gjk= # ARTIFACTORY_PASSWORD
  matrix:
  - RELEASE_BUILD=true
  - QUICK_BUILD=true
matrix:
  exclude:
  - jdk: openjdk6
    env: RELEASE_BUILD=true
  - jdk: oraclejdk8
    env: RELEASE_BUILD=true
